[package]
name = "tls-api-rustls"
version = "0.3.0"
authors = ["Stepan Koltsov <stepan.koltsov@gmail.com>"]
description = "TLS API implementation over rustls crate"
license = "MIT/Apache-2.0"
repository = "https://github.com/stepancheg/rust-tls-api/"
keywords = ["tls"]
edition = "2018"

[badges]
travis-ci = { repository = "https://github.com/stepancheg/rust-tls-api/", branch = "master" }

[dependencies]
rustls = { version = "0.15.2", features = ["dangerous_configuration"] }
futures = { version = "0.3.0", features = ["async-await"] }
tokio = { version = "~0.2.6", features = [] }
tls-api = { path = "../api", version = "=0.3.0" }
webpki       = "0.19.1"
webpki-roots = "0.16.0"

[dev-dependencies]
tls-api-test = { path = "../api-test", version = "=0.3.0" }
