[package]
name = "tls-api-test"
version = "0.4.0"
authors = ["Stepan Koltsov <stepan.koltsov@gmail.com>"]
description = "TLS API without implementation"
license = "MIT/Apache-2.0"
repository = "https://github.com/stepancheg/rust-tls-api/"
keywords = ["tls"]
edition = "2018"

[badges]
travis-ci = { repository = "https://github.com/stepancheg/rust-tls-api/", branch = "master" }

[dependencies]
tls-api = { path = "../api", version = "=0.4.0" }
log        = "0.4"
env_logger = "0.5"

pem        = "0.6.*"
webpki     = "0.21.2"
untrusted  = "0.6.*"

tokio = { version = "~0.2.6", features = ["tcp", "io-util", "dns"] }
